### ISSUE TITLE
Will not print the list from list_actions

### ISSUE THREAD

**Issue by rhickstedjr** [M-J-Murray/MAMEToolkit#10]
parallels@parallels-Parallels-Virtual-Platform:~$ cat sfla.py
from MAMEToolkit.emulator import list_actions

roms_path = "roms/"  # Replace this with the path to your ROMs
game_id = "sfiii3n"
print(list_actions(roms_path, game_id))

Seeing:

arallels@parallels-Parallels-Virtual-Platform:~$ python3.6 ./sfla.py 
unzip: /home/parallels/roms/sfiii3.zip couldn't find ECD in last 64KiB
Expected output but received nothing from emulator after 'for k,v in pairs(iop.ports) do print(k) end'
Traceback (most recent call last):
  File "./sfla.py", line 5, in <module>
    print(list_actions(roms_path, game_id))
  File "/home/parallels/.local/lib/python3.6/site-packages/MAMEToolkit/emulator/Emulator.py", line 19, in list_actions
    ports = console.writeln("for k,v in pairs(iop.ports) do print(k) end", expect_output=True, timeout=0.5)
  File "/home/parallels/.local/lib/python3.6/site-packages/MAMEToolkit/emulator/Console.py", line 71, in writeln
    raise IOError(error)
OSError: Expected output but received nothing from emulator after 'for k,v in pairs(iop.ports) do print(k) end'

Thanks,

Rick

**Comment by rhickstedjr** [comment]
I built and I am using the mame64 custom source:  The modified MAME implementation can be found at [https://github.com/M-J-Murray/mame]

**Comment by rhickstedjr** [comment]
info on mame64 binary in use:

parallels@parallels-Parallels-Virtual-Platform:~$ which mame
/usr/local/bin/mame
parallels@parallels-Parallels-Virtual-Platform:~$ ls -l /usr/local/bin/mame
-rwxr-xr-x 1 root root 283795616 Feb 11 11:12 /usr/local/bin/mame
parallels@parallels-Parallels-Virtual-Platform:~$ ls -l ./mame-master/mame64 
-rwxr-xr-x 1 parallels parallels 283795616 Feb 11 15:58 ./mame-master/mame64

**Comment by rhickstedjr** [comment]
I also have a good sfiii3n rom...

**Comment by M-J-Murray** [comment]
You do not need to compile your own instance of mame. When you pip install the library the custom compiled mame will be downloaded with the library code. I'm not exactly sure what is causing this. But a good place to start would be to download the official MAME emulator and try and get your game running on that first.

**Comment by rhickstedjr** [comment]
Removed my mame build and see the same issue?

parallels@parallels-Parallels-Virtual-Platform:~$ python3.6 ./sfla.py
Expected output but received nothing from emulator after 'for k,v in pairs(iop.ports) do print(k) end'
Traceback (most recent call last):
  File "./sfla.py", line 5, in <module>
    print(list_actions(roms_path, game_id))
  File "/home/parallels/.local/lib/python3.6/site-packages/MAMEToolkit/emulator/Emulator.py", line 19, in list_actions
    ports = console.writeln("for k,v in pairs(iop.ports) do print(k) end", expect_output=True, timeout=0.5)
  File "/home/parallels/.local/lib/python3.6/site-packages/MAMEToolkit/emulator/Console.py", line 71, in writeln
    raise IOError(error)
OSError: Expected output but received nothing from emulator after 'for k,v in pairs(iop.ports) do print(k) end'

**Comment by rhickstedjr** [comment]
Note the game runs just fine.

**Comment by rhickstedjr** [comment]
Found the issue the timeout was too low:
parallels@parallels-Parallels-Virtual-Platform:~$ python3.6 ./sfla.py
[{'port': ':EXTRA', 'field': 'P2 Forward Kick'}, {'port': ':EXTRA', 'field': 'P1 Roundhouse Kick'}, {'port': ':EXTRA', 'field': 'P1 Short Kick'}, {'port': ':EXTRA', 'field': 'P2 Short Kick'}, {'port': ':EXTRA', 'field': 'P1 Forward Kick'}, {'port': ':INPUTS', 'field': 'P1 Up'}, {'port': ':INPUTS', 'field': 'P2 Down'}, {'port': ':INPUTS', 'field': 'P1 Down'}, {'port': ':INPUTS', 'field': 'P2 Strong Punch'}, {'port': ':INPUTS', 'field': 'P1 Fierce Punch'}, {'port': ':INPUTS', 'field': 'P2 Right'}, {'port': ':INPUTS', 'field': 'Coin 2'}, {'port': ':INPUTS', 'field': 'P1 Right'}, {'port': ':INPUTS', 'field': 'P2 Roundhouse Kick'}, {'port': ':INPUTS', 'field': '2 Players Start'}, {'port': ':INPUTS', 'field': 'Coin 1'}, {'port': ':INPUTS', 'field': 'Service Mode'}, {'port': ':INPUTS', 'field': '1 Player Start'}, {'port': ':INPUTS', 'field': 'Service 1'}, {'port': ':INPUTS', 'field': 'P2 Up'}, {'port': ':INPUTS', 'field': 'P2 Fierce Punch'}, {'port': ':INPUTS', 'field': 'P1 Strong Punch'}, {'port': ':INPUTS', 'field': 'P2 Jab Punch'}, {'port': ':INPUTS', 'field': 'P1 Jab Punch'}, {'port': ':INPUTS', 'field': 'P1 Left'}, {'port': ':INPUTS', 'field': 'P2 Left'}, {'port': ':scsi:1:cdrom:SCSI_ID', 'field': 'SCSI ID'}]
parallels@parallels-Parallels-Virtual-Platform:~$ 

Fixed this line:

    ports = console.writeln("for k,v in pairs(iop.ports) do print(k) end", expect_output=True, timeout=5.0)

**Comment by rhickstedjr** [comment]
I am running in a Ubuntu 18.04 VM under Mac OS X.  Seems .5 is not a sufficient timeout.

**Comment by rhickstedjr** [comment]
Under the Simple ConvNet Agent section:

**Comment by M-J-Murray** [comment]
I'll change the default timeout to be 5 seconds.
