### ISSUE TITLE
Enable sound when throttle = True?

### ISSUE THREAD

**Issue by RielFox** [M-J-Murray/MAMEToolkit#14]
Hey there,
I'm basing an agent on your framework. It's very helpful.
One question, when I want to demonstrate my agent play in real-time with frame_ratio=1 and throttle = True, is it possible to enable sound? Of course, I will use faster settings while training.
Thanks in advance!

**Comment by zgxlogic** [comment]
Hi RielFox, I have the exact same question.

Have you figured out a way to do it?

**Comment by zgxlogic** [comment]
Just figured out:

In Console.py, there is one line:
command = f"exec {binary_path} -rompath '{str(Path(roms_path).absolute())}' -pluginspath plugins -skip_gameinfo -sound none -window -nomaximize -console "+game_id

The "-sound none" disables the sound.

After I change it to 

        command = f"exec ./mame -rompath '{str(Path(roms_path).absolute())}' -pluginspath plugins -skip_gameinfo "
        if not throttle:
            command += " -sound none"
        command += " -console "+game_id

I was able to get the sound when throttled.

**Comment by RielFox** [comment]
Hey,

That worked! Thanks! 
It will be a nice addition to the presentation of my agents.
