### ISSUE TITLE
Have you considered providing a gym interface?

### ISSUE THREAD

**Issue by guanzeying** [M-J-Murray/MAMEToolkit#22]
So we can use baselines RL Algorithm etc.

**Comment by M-J-Murray** [comment]
That is something that could definately be added.
I have mainly worked with PyTorch and Tensorflow, so the new API would be based around them.
This library still has a lot of room to grow, but hopefully with the new sponsorship program that should be possible. See https://github.com/sponsors/M-J-Murray for more information.
