### ISSUE TITLE
OSError: Expected output but received nothing from emulator after 'print(manager:machine().screens[":screen"])'

### ISSUE THREAD

**Issue by kteaw0110** [M-J-Murray/MAMEToolkit#3]
I tried to execute your demo code and I got a OSError.
**OSError: Expected output but received nothing from emulator after 'print(manager:machine().screens[":screen"])'**

import random
from MAMEToolkit.sf_environment import Environment

roms_path = "roms/"  # Replace this with the path to your ROMs
env = Environment("env1", roms_path)
env.start()
while True:
    move_action = random.randint(0, 8)
    attack_action = random.randint(0, 9)
    frames, reward, round_done, stage_done, game_done = env.step(move_action, attack_action)
    if game_done:
        env.new_game()
    elif stage_done:
        env.next_stage()
    elif round_done:
        env.next_round()

How can I fix it?
I use Ubuntu 16.04.

**Comment by M-J-Murray** [comment]
I've attempted to fix the problem. If you uninstall then reinstall the library you should get version 1.0.2. This should have the fixed version.
