### ISSUE TITLE
Error while loading shared lib ? 

### ISSUE THREAD

**Issue by MoMe36** [M-J-Murray/MAMEToolkit#5]
Hello, 

I'm trying to get the ```see_games``` to run or the random agent, but I get the following error message: 

```bash
./mame: error while loading shared libraries: libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory
```

Could I get some help ? Thanks !

**Comment by kyuhyoung** [comment]
> Hello,
> 
> I'm trying to get the `see_games` to run or the random agent, but I get the following error message:
> 
> ```shell
> ./mame: error while loading shared libraries: libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory
> ```
> 
> Could I get some help ? Thanks !

For me, the following worked.
```sudo apt install libsdl2-ttf-2.0-0```

**Comment by MoMe36** [comment]
It did ! Thanks ;)
