### ISSUE TITLE
how to run reinforcement learning？ are you used tenforflow?

### ISSUE THREAD

**Issue by 82604716** [M-J-Murray/MAMEToolkit#8]
how to run reinforcement learning？ are you used tenforflow?  can you share your reinforcement learning environment ?

**Comment by M-J-Murray** [comment]
The framework itself doesn't provide any tools for generating reinforcement learning algorithms. However, you can find some examples of how you can use PyTorch or TensorFlow here: https://github.com/M-J-Murray/SFAgents
