### ISSUE TITLE
SF3 wont work

### ISSUE THREAD

**Issue by cjbarb7** [M-J-Murray/MAMEToolkit#9]
I download the SF3 rom and I keep encountering this issues

sfiii3_japan_nocd.29f400.u2 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm1.0 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm1.1 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm1.2 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm1.3 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm2.0 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm2.1 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm2.2 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm2.3 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm3.0 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm3.1 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm3.2 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm3.3 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm3.4 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm3.5 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm3.6 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm3.7 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm4.0 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm4.1 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm4.2 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm4.3 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm4.4 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm4.5 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm4.6 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm4.7 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm5.0 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm5.1 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm5.2 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm5.3 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm5.4 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm5.5 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm5.6 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm5.7 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm6.0 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm6.1 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm6.2 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm6.3 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm6.4 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm6.5 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm6.6 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
sfiii3-simm6.7 NOT FOUND (tried in sfiii3n sfiii3 sfiii3n)
Fatal error: Required files are missing, the machine cannot be run.

I have those files in the rom path that I am sending to, yet I still encounter this issue.

**Comment by M-J-Murray** [comment]
Make sure you have the japan sfiii3n edition rom. Once you have the compressed rom file, point the library at the directory containing this file. This is a common MAME error.

**Comment by cjbarb7** [comment]
Thank you, that fixed it.

**Comment by consciousgaze** [comment]
is the compressed rom file a zip file? I have a zip file which contains files like sfiii3_japan_nocd.29f400.u2, sfiii3n-simm1.0 etc. It is put in /game/ROMs/a.zip. But when i am trying to start with  env = Environment("env1", " /game/ROMs/a.zip") it still gives me the same error
